services:
  db:
    image: postgres
    container_name: docker-db-test
    restart: always
    ports:
      - "6543:5432"
    env_file:
      - .env.test

  node_app:
    container_name: students-ci-cd-test
    build: .
    ports:
      - "6528:5000"
    depends_on:
      - db
    env_file:
      - .env.test
